### ISSUE TITLE
[Can estimated kernels(spatially variant) be used to deconvolution debluring?]

### ISSUE THREAD

**Issue by CaptainEven** [JingyunLiang/MANet#4]
Can estimated kernels(spatially variant) be applied to deconvolution debluring explicitly, using FFT and wiener filter?

**Comment by JingyunLiang** [comment]
It is possible, but I didn't try it. Note that for deconvolution, the kernels are often much more complex (e.g., motion blur). It may be harder to estimate the kernels accurately, though one good thing is that there is no downscaling in deconvolution. We can summarize them as follows:

image super-resolution: downscaling (hard, much loss of information) + blur (often assumed to be simple, at most anisotropic Gaussian) + noise

image deblurring: blur only (often motion blur kernels, as Gaussian blurs are too easy for this task, even traditional methods may solve it well) + noise

**Comment by CaptainEven** [comment]
@JingyunLiang Thanks for the explanation! I got it, and i 'll try this maybe when i'm free .
